### ISSUE TITLE
Why output picture so dark!!! I use the pretrained model. Need any other operation ???

### ISSUE THREAD

**Issue by StudentZhangxu** [cchen156/Learning-to-See-in-the-Dark#44] opened 2018-07-28 08:53 UTC
**I download the pretrained model and run 'test_Sony.py'.But the output is very dark!**

![screenshot from 2018-07-28 04-51-01](https://user-images.githubusercontent.com/27423436/43354945-a60affc4-9286-11e8-8971-f6d8ddef07c4.png)

**Comment by StudentZhangxu** [comment] 2018-07-28 09:04
I try to scale the 'output' to the same mean of 'gt_scale', then the problem is more serious! I do not kown what's wrong?
![screenshot from 2018-07-28 04-59-05](https://user-images.githubusercontent.com/27423436/43355040-212370d2-9288-11e8-819a-c681ce6a0b0a.png)

**Comment by StudentZhangxu** [comment] 2018-07-28 13:11
@cchen156 Could you please figure out what's wrong?

**Comment by oneTaken** [comment] 2018-08-07 08:32
I'm also using this pretrained model. The results is interesting.
And you can close this issue if the problem is solved well.

**Closed** 2018-09-04 08:39 UTC

**Comment by lyn-max** [comment] 2019-08-26 02:37
@StudentZhangxu Have you found the 'checkpoint' and 'model.cpkt.index' files?
